Repository alphagov/govuk-design-guide, pull requests merged in 2024-10, with the labels that each got.

#74 Add opengraph image and suffix to title
  docs/assets/opengraph.png
  eleventy.config.js
Labels: enhancement

#76 Update layout template
  _includes/layouts/component-documentation.njk
  _includes/layouts/frontend-template-documentation.njk
  _includes/layouts/homepage.njk
  _includes/layouts/landing-page.njk
  _includes/layouts/main.njk
  _includes/layouts/pattern-documentation.njk
Labels: enhancement

#73 Transfer existing frontend template docs to template
  _includes/layouts/frontend-template-documentation.njk
  docs/components/*components-documentation-template.md
  docs/components/attachment.md
  docs/components/breadcrumbs.md
  docs/components/content-list.md
  docs/components/feedback.md
  docs/components/global-banner.md
  docs/components/print-link.md
  docs/frontend-templates/*frontend-template-documentation-template.md
  docs/frontend-templates/answer.md
  docs/frontend-templates/calendar.md
  docs/frontend-templates/completed-transaction.md
  docs/frontend-templates/detailed-guide.md
  docs/frontend-templates/document-collections.md
  docs/frontend-templates/finder/case-studies-finder.md
  docs/frontend-templates/finder/departments-agencies-public-bodies-finder.md
  docs/frontend-templates/finder/groups-finder.md
  docs/frontend-templates/finder/hmrc-contacts-finder.md
  docs/frontend-templates/finder/index.md
  docs/frontend-templates/finder/people-finder.md
  docs/frontend-templates/finder/search.md
  docs/frontend-templates/finder/specialist-document-finder.md
  docs/frontend-templates/finder/statistical-data-sets-finder.md
  docs/frontend-templates/finder/supergroup-finder.md
  docs/frontend-templates/finder/topical-events-finder.md
  docs/frontend-templates/finder/world-organisation-finder.md
  docs/frontend-templates/guide.md
  docs/frontend-templates/homepage.md
  docs/frontend-templates/mainstream-browse/index.md
  docs/frontend-templates/mainstream-browse/level-one.md
  docs/frontend-templates/mainstream-browse/level-two.md
  docs/frontend-templates/smart-answer/github-smart-answer.md
  docs/frontend-templates/smart-answer/index.md
  docs/frontend-templates/smart-answer/simple-smart-answer.md
  docs/frontend-templates/special-route.md
  docs/frontend-templates/step-by-step-nav.md
  docs/frontend-templates/topical-events/about.md
  docs/frontend-templates/topical-events/index.md
  docs/frontend-templates/transaction.md
  docs/patterns/*patterns-documentation-template.md
  docs/patterns/search-filter.md
Labels: documentation

#72 Add analytics and cookie banner, cookie page
  _includes/layouts/cookies.njk
  _includes/layouts/main.njk
  _includes/macros/cookie-banner.njk
  docs/cookies/index.md
  docs/javascripts/application.mjs
  docs/javascripts/components/analytics.mjs
  docs/javascripts/components/cookie-banner.mjs
  docs/javascripts/components/cookie-functions.mjs
  docs/javascripts/components/cookies-page.mjs
  eleventy.config.js
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#83 Moved images into a folder to keep the root clean.
  docs/assets/images/components.svg
  docs/assets/images/frontend-templates.svg
  docs/assets/images/get-involved.svg
  docs/assets/images/homepage.svg
  docs/assets/images/opengraph.png
  docs/assets/images/patterns.svg
  docs/community/index.md
  docs/components/index.md
  docs/frontend-templates/index.md
  docs/index.md
  docs/patterns/index.md
  eleventy.config.js
Labels: enhancement

#86 Update template file names
  README.md
  docs/community/questions-and-answers.md
  docs/components/*component-documentation-template.md
  docs/patterns/*pattern-documentation-template.md
Labels: enhancement

#87 Update file names for component and pattern template
  README.md
  docs/community/questions-and-answers.md
  docs/components/*component-documentation-template.md
  docs/patterns/*pattern-documentation-template.md
Labels: enhancement

#80 Single page notification
  docs/components/single_page_notification_button.md
Labels: new documentation, component

#85 Create issues template
  .github/ISSUE_TEMPLATE/01-new-component.yml
  .github/ISSUE_TEMPLATE/02-new-pattern.yml
  .github/ISSUE_TEMPLATE/03-new-frontend-template.yml
Labels: enhancement

#90 Resolve issues template
  .github/ISSUE_TEMPLATE/01-new-component.yml
  .github/ISSUE_TEMPLATE/02-new-pattern.yml
  .github/ISSUE_TEMPLATE/03-new-frontend-template.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#93 Resolve information mapping issue
  .github/ISSUE_TEMPLATE/01-new-component.yml
  .github/ISSUE_TEMPLATE/02-new-pattern.yml
  .github/ISSUE_TEMPLATE/03-new-frontend-template.yml
Labels: enhancement

#94 Created templates for updating exisitng documentation
  .github/ISSUE_TEMPLATE/04-update-component.yml
  .github/ISSUE_TEMPLATE/05-update-pattern.yml
  .github/ISSUE_TEMPLATE/06-update-frontend-template.yml
Labels: enhancement

#100 Template to report bugs
  .github/ISSUE_TEMPLATE/08-bug-template.yml
Labels: enhancement

#101 Template to report issues on component+patterns+frontendTemplates
  .github/ISSUE_TEMPLATE/09-component-issue.yml
  .github/ISSUE_TEMPLATE/10-pattern-issue.yml
  .github/ISSUE_TEMPLATE/11-frontend-template-issue.yml
Labels: enhancement

#102 Update link to report issue
  _includes/partials/instructions-report-issue.njk
  _includes/partials/issues.njk
  docs/components/*component-documentation-template.md
  docs/components/attachment.md
  docs/components/breadcrumbs.md
  docs/components/content-list.md
  docs/components/feedback.md
  docs/components/global-banner.md
  docs/components/print-link.md
  docs/components/single-page-notification-button.md
  docs/frontend-templates/*frontend-template-documentation-template.md
  docs/frontend-templates/answer.md
  docs/frontend-templates/calendar.md
  docs/frontend-templates/completed-transaction.md
  docs/frontend-templates/detailed-guide.md
  docs/frontend-templates/document-collections.md
  docs/frontend-templates/finder/case-studies-finder.md
  docs/frontend-templates/finder/departments-agencies-public-bodies-finder.md
  docs/frontend-templates/finder/groups-finder.md
  docs/frontend-templates/finder/hmrc-contacts-finder.md
  docs/frontend-templates/finder/index.md
  docs/frontend-templates/finder/people-finder.md
  docs/frontend-templates/finder/search.md
  docs/frontend-templates/finder/specialist-document-finder.md
  docs/frontend-templates/finder/statistical-data-sets-finder.md
  docs/frontend-templates/finder/supergroup-finder.md
  docs/frontend-templates/finder/topical-events-finder.md
  docs/frontend-templates/finder/world-organisation-finder.md
  docs/frontend-templates/guide.md
  docs/frontend-templates/homepage.md
  docs/frontend-templates/mainstream-browse/index.md
  docs/frontend-templates/mainstream-browse/level-one.md
  docs/frontend-templates/mainstream-browse/level-two.md
  docs/frontend-templates/smart-answer/github-smart-answer.md
  docs/frontend-templates/smart-answer/index.md
  docs/frontend-templates/smart-answer/simple-smart-answer.md
  docs/frontend-templates/special-route.md
  docs/frontend-templates/step-by-step-nav.md
  docs/frontend-templates/topical-events/about.md
  docs/frontend-templates/topical-events/index.md
  docs/frontend-templates/transaction.md
  docs/patterns/*pattern-documentation-template.md
  docs/patterns/search-filter.md
Labels: update documentation, enhancement
