Repository alphagov/govuk-design-guide, pull requests merged in 2024-12, with the labels that each got.

#112 Update links on q&a page
  docs/community/questions-and-answers.md
Labels: update documentation

#118 Streamlined dates
  docs/components/global-banner.md
  docs/components/single-page-notification-button.md
  docs/frontend-templates/answer.md
  docs/frontend-templates/finder/index.md
  docs/frontend-templates/guide.md
  docs/frontend-templates/homepage.md
  docs/frontend-templates/mainstream-browse/index.md
Labels: update documentation

#133 Add a custom title value for homepage
  _includes/layouts/homepage.njk
  docs/index.md
Labels: update documentation, enhancement, accessibility

#136 Updated name of this package
  package-lock.json
Labels: good first issue

#137 Update name via Package.JSON
  package-lock.json
  package.json
Labels: invalid

#139 Update ordering when inputting insights
  _includes/partials/insights.njk
  docs/components/content-list.md
  docs/components/global-banner.md
  docs/frontend-templates/answer.md
  docs/frontend-templates/finder/index.md
  docs/frontend-templates/guide.md
  docs/frontend-templates/homepage.md
  docs/frontend-templates/mainstream-browse/index.md
Labels: enhancement

#138 small changes, mainly typos
  docs/components/attachment.md
  docs/components/breadcrumbs.md
  docs/components/content-list.md
  docs/components/feedback.md
  docs/components/global-banner.md
  docs/components/print-link.md
  docs/components/single-page-notification-button.md
  docs/frontend-templates/document-collections.md
  docs/frontend-templates/mainstream-browse/index.md
  docs/frontend-templates/mainstream-browse/level-two.md
Labels: update documentation

#151 Update quotation mark
  _includes/partials/instructions-report-issue.njk
Labels: update documentation

#152 Adding research to Mainstream Browse
  docs/frontend-templates/mainstream-browse/index.md
Labels: update documentation, frontend template

#145 Adding issues to components (breadcrumbs)
  docs/components/breadcrumbs.md
Labels: component

#157 Removed conditional in help improve title
  _includes/partials/help-improve.njk
Labels: enhancement

#161 changes to print link WIP
  docs/components/print-link.md
Labels: update documentation, component

#158 Edited text and added an issue
  docs/components/feedback.md
Labels: update documentation, component

#168 84 document previous and next navigation
  docs/components/previous-and-next-navigation.md
Labels: new documentation, component

#167 added issues and some additional descriptions
  docs/components/single-page-notification-button.md
Labels: update documentation, component

#184 reworded the summaries of insights to be more informative.
  docs/frontend-templates/mainstream-browse/index.md
Labels: update documentation, frontend template

#183 attempted to give better descriptions for the insights documents. Fee…
  docs/frontend-templates/homepage.md
Labels: update documentation, frontend template

#182 just made the description more precise on one of the insights.
  docs/frontend-templates/finder/index.md
Labels: update documentation, frontend template

#179 just two tiny text edits
  docs/frontend-templates/answer.md
Labels: update documentation, frontend template

#178 170 create documentation for emergency banner
  docs/components/emergency-banner.md
Labels: new documentation, component
