Repository alphagov/govuk-design-guide, pull requests merged in 2025-01, with the labels that each got.

#181 Search autocomplete component documentation
  docs/components/search-autocomplete.md
Labels: new documentation, component

#207 Reveal sub-navigation
  _includes/partials/sub-navigation.njk
Labels: enhancement, accessibility

#205 fixed typo on line 94
  docs/components/search-autocomplete.md
Labels: update documentation, component

#209 Updated humans.txt to include GIFT week participants
  docs/humans.txt
Labels: enhancement

#214 Updated documentation about how document collections work
  docs/frontend-templates/document-collections.md
Labels: update documentation, frontend template
